name: ci

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: valgrind_level=0
          tags: grimbough/test:vl0
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: valgrind_level=1
          tags: grimbough/test:vl1
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: valgrind_level=2
          tags: grimbough/test:vl2
          